<a href="https://colab.research.google.com/github/JSM1211/AI2023-2_JoelSanchez/blob/main/PY_AI5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as joel

aux=joel.array([1,2,4,5])
print(aux)
# Tipo de arreglo
print(aux.shape)
print('------------------------------')

aux=joel.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))
print('------------------------------')

tmp=joel.zeros((4,4))
print(tmp)
print('------------------------------')


tmp=joel.full((4,4),5)
print(tmp)
print('------------------------------')


tmp=joel.eye(4,4)
print(tmp)
print('------------------------------')


tmp=joel.ones((4,4))
print(tmp)
print('------------------------------')

[1 2 4 5]
(4,)
------------------------------
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
------------------------------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
------------------------------


In [ ]:
tmp=10*joel.random.random((4,4))
print(tmp)
print('------------------------------')

[[1.05878222e+00 4.20914530e+00 2.91147877e+00 2.14197096e+00]
 [3.63564831e+00 7.14228698e+00 7.55943547e+00 3.50307359e-01]
 [5.76617167e-03 7.01335222e+00 4.62343087e+00 4.68070243e+00]
 [3.65067707e+00 3.46654313e+00 3.44819459e+00 9.51938064e+00]]
------------------------------


In [ ]:
print(tmp[:2,:2])
print('------------------------------')
print(tmp[2:4,2:4])

[[1.05878222 4.2091453 ]
 [3.63564831 7.14228698]]
------------------------------
[[4.62343087 4.68070243]
 [3.44819459 9.51938064]]


In [ ]:
print(tmp[1,1])
print('------------------------------')
print(tmp[2,2])
print('------------------------------')

7.1422869827914335
------------------------------
4.623430874447384
------------------------------


In [ ]:
tmp=10*joel.random.random((4,4))
print(tmp)

[[2.34082218 8.72393779 7.21747908 7.93972984]
 [2.11960474 8.33909745 7.9284533  4.94916212]
 [6.62832628 9.21516991 3.76406484 3.31658224]
 [7.01957764 2.58311717 1.22269817 4.33557488]]


In [ ]:
mascara=tmp>5
print(mascara)
print('------------------------------')
print(tmp[mascara])
print('------------------------------')

[[False  True  True  True]
 [False  True  True False]
 [ True  True False False]
 [ True False False False]]
------------------------------
[8.72393779 7.21747908 7.93972984 8.33909745 7.9284533  6.62832628
 9.21516991 7.01957764]
------------------------------


In [ ]:
mask = (tmp >=2) & (tmp<=4)
print(tmp[mask])

[2.34082218 2.11960474 3.76406484 3.31658224 2.58311717]


In [ ]:
tmp = joel.random.randint(0, 11, size=(4, 4))
print(tmp)
print('----------------------------------')
mask = joel.mod(tmp, 2) == 0
print(tmp[mask])


[[ 6  9  6 10]
 [10  0  2  3]
 [ 1  2  8  7]
 [ 4 10  2  5]]
----------------------------------
[ 6  6 10 10  0  2  2  8  4 10  2]
