<a href="https://colab.research.google.com/github/JSM1211/AI2023-2_JoelSanchez/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

#create an array with random inteher values between 1 and 10
a = np.random.randint(1, 11, size=(3,4))
b = np.random.randint(1, 11, size=(3,4))
print(a)
print(b)
print(a.shape)
print(b.shape)
print('Adding numbers')
#plus
print(a+b)
print('Subtracting numbers')
#minus
print(a-b)
print('Multiplication numbers')
#times
print(a*b)


print('Add')
print(np.add(a,b))
print('Substract')
print(np.multiply(a,b))
print('Multiply')
print(np.subtract(a,b))
print('Divide')
print(np.divide(a,b))

[[9 6 8 6]
 [7 8 6 9]
 [9 2 9 5]]
[[ 7  8  8  6]
 [ 8 10  1  3]
 [ 6  2 10  6]]
(3, 4)
(3, 4)
Adding numbers
[[16 14 16 12]
 [15 18  7 12]
 [15  4 19 11]]
Subtracting numbers
[[ 2 -2  0  0]
 [-1 -2  5  6]
 [ 3  0 -1 -1]]
Multiplication numbers
[[63 48 64 36]
 [56 80  6 27]
 [54  4 90 30]]
Add
[[16 14 16 12]
 [15 18  7 12]
 [15  4 19 11]]
Substract
[[63 48 64 36]
 [56 80  6 27]
 [54  4 90 30]]
Multiply
[[ 2 -2  0  0]
 [-1 -2  5  6]
 [ 3  0 -1 -1]]
Divide
[[1.28571429 0.75       1.         1.        ]
 [0.875      0.8        6.         3.        ]
 [1.5        1.         0.9        0.83333333]]


In [13]:
m1 = np.random.randint(1, 11, size=(3,4))
m2 = np.random.randint(1, 11, size=(4,8))
print('Matriz 1')
print(m1)
print(m1.shape)
print('Matriz 2')
print(m2)
print(m2.shape)
print('-------------------------')
print('Forma 1')
print(np.dot(m1,m2))
print('Forma 2')
print(m1.dot(m2))
print(np.dot(m1,m2).shape)


Matriz 1
[[ 9  7  8  1]
 [ 9  8  9 10]
 [ 6  9  3 10]]
(3, 4)
Matriz 2
[[10  9  5  1  7  6  8  9]
 [ 1  8  2  3  3  7  8  2]
 [ 4  6  4  3  4  6  3  9]
 [ 6  2 10  3  4  5  1  3]]
(4, 8)
-------------------------
Forma 1
[[135 187 101  57 120 156 153 170]
 [194 219 197  90 163 214 173 208]
 [141 164 160  72 121 167 139 129]]
Forma 2
[[135 187 101  57 120 156 153 170]
 [194 219 197  90 163 214 173 208]
 [141 164 160  72 121 167 139 129]]
(3, 8)


In [16]:
a = np.random.randint(1, 11, size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[3 3]
 [7 7]]
[[3 7]
 [3 7]]


In [22]:
#broadcast
x = np.random.randint(1, 11, size=(4,3))
y = np.array([1,0,2])

print(x.shape)
print(y.shape)

z=np.empty_like(x)
print('---------------------')
print(x)
print('---------------------')
print(y)
print(z.shape)
print('---------------------')
print(z)


(4, 3)
(3,)
---------------------
[[ 4  4 10]
 [10  7  7]
 [ 4  7  6]
 [ 6  5  6]]
---------------------
[1 0 2]
(4, 3)
---------------------
[[6 8 5]
 [2 9 3]
 [3 3 7]
 [3 6 1]]


In [24]:
for i in range(4):
  z[i,:]=x[i,:]+y
print(z)

[[ 5  4 12]
 [11  7  9]
 [ 5  7  8]
 [ 7  5  8]]


In [29]:
z=x+y
print(z)

[[ 5  4 12]
 [11  7  9]
 [ 5  7  8]
 [ 7  5  8]]


In [46]:
#para comentar varias lineas de codigo se usa triple comillas simples """  """

a=np.array([1,2,3])
print(a)
print('-----------------')

b = np.full((6,3),[a])
print(b)
print('-----------------')

c= np.tile(a,(6,1))
print(c)


[[ 4  8  1  6  9  7]
 [10  1  1  3  6  6]
 [ 9  7  8  1  1  1]
 [ 7 10  1  4  3  3]
 [ 2  1  1  7  5  2]
 [ 4  2  3  3 10  2]]


In [54]:
m1 = np.random.randint(0, 10, size=(6,6))
print(m1)
aux=np.mean(m1)
print(aux)

np.mean(m1, axis=1) #promedio por filas
np.mean(m1, axis=0) #promedio por filas

print('Promedio por filas')
print(np.mean(m1, axis=1))
print('Promedio por columnas')
print(np.mean(m1, axis=0))

[[8 2 2 6 7 3]
 [1 3 2 3 9 7]
 [6 8 5 2 2 7]
 [6 7 0 6 3 2]
 [7 1 2 9 7 8]
 [6 6 3 4 4 4]]
4.666666666666667
Promedio por filas
[4.66666667 4.16666667 5.         4.         5.66666667 4.5       ]
Promedio por columnas
[5.66666667 4.5        2.33333333 5.         5.33333333 5.16666667]
